CREATE DATABASE ALOJAMIENTOSIKERSANCHEZ;
GO
USE ALOJAMIENTOSIKERSANCHEZ;
GO

CREATE TABLE CATEGORIAS (
    ID_CATEGORIA INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE ESTABLECIMIENTOS (
    ID_ESTABLECIMIENTO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_COMERCIAL VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100),
    ID_CATEGORIA INT NOT NULL,
    CONSTRAINT FK_ESTABLECIMIENTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) 
        REFERENCES CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE UNIDADES_ALOJAMIENTO (
    ID_ESTABLECIMIENTO INT NOT NULL,
    NUMERO_UNIDAD INT NOT NULL,
    NOMBRE_UNIDAD VARCHAR(50),
    CAPACIDAD_MAXIMA INT NOT NULL,
    ESTADO VARCHAR(20) CHECK (ESTADO IN ('DISPONIBLE', 'OCUPADA', 'MANTENIMIENTO')) DEFAULT 'DISPONIBLE',
    PRECIO_BASE_NOCHE FLOAT NOT NULL,
    DESCRIPCION VARCHAR(MAX),
    PRIMARY KEY (ID_ESTABLECIMIENTO, NUMERO_UNIDAD),
    CONSTRAINT FK_UNIDAD_ESTABLECIMIENTO FOREIGN KEY (ID_ESTABLECIMIENTO) 
        REFERENCES ESTABLECIMIENTOS(ID_ESTABLECIMIENTO)
);

CREATE TABLE CLIENTELA (
    ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
    DNI_NIE VARCHAR(20) UNIQUE NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100)
);

CREATE TABLE RESERVAS (
    ID_RESERVA INT PRIMARY KEY IDENTITY(1,1),
    ID_CLIENTE INT NOT NULL,
    ID_ESTABLECIMIENTO INT NOT NULL,
    NUMERO_UNIDAD INT NOT NULL,
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    FECHA_ENTRADA DATE NOT NULL,
    FECHA_SALIDA DATE NOT NULL,
    NUMERO_PERSONAS INT NOT NULL,
    ESTADO VARCHAR(15) CHECK (ESTADO IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'FINALIZADA')) DEFAULT 'PENDIENTE',
    FIANZA FLOAT NULL,
    IMPORTE_ESTIMADO FLOAT NOT NULL,
    CONSTRAINT FK_RESERVA_UNIDAD FOREIGN KEY (ID_ESTABLECIMIENTO, NUMERO_UNIDAD) 
        REFERENCES UNIDADES_ALOJAMIENTO(ID_ESTABLECIMIENTO, NUMERO_UNIDAD),
    CONSTRAINT FK_RESERVA_CLIENTE FOREIGN KEY (ID_CLIENTE) 
        REFERENCES CLIENTELA(ID_CLIENTE)
);

CREATE TABLE PAGOS (
    ID_PAGO INT PRIMARY KEY IDENTITY(1,1),
    ID_RESERVA INT NOT NULL,
    IMPORTE FLOAT NOT NULL,
    FECHA_PAGO DATETIME NULL,
    METODO_PAGO VARCHAR(50),
    CONSTRAINT FK_PAGO_RESERVA FOREIGN KEY (ID_RESERVA) 
        REFERENCES RESERVAS(ID_RESERVA)
);