USE ALOJAMIENTOSIKERSANCHEZ;
GO

-- 1. BORRADO DE TABLAS (Orden inverso a su creación por las Foreign Keys)
DROP TABLE IF EXISTS PAGOS;
DROP TABLE IF EXISTS RESERVAS;
DROP TABLE IF EXISTS CLIENTELA;
DROP TABLE IF EXISTS UNIDADES_ALOJAMIENTO;
DROP TABLE IF EXISTS ESTABLECIMIENTOS;
DROP TABLE IF EXISTS CATEGORIAS;
GO

-- 2. CREACIÓN DE TABLAS
CREATE TABLE CATEGORIAS (
    ID_CATEGORIA INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE ESTABLECIMIENTOS (
    ID_ESTABLECIMIENTO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_COMERCIAL VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100),
    ID_CATEGORIA INT NOT NULL,
    CONSTRAINT FK_ESTABLECIMIENTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) 
        REFERENCES CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE UNIDADES_ALOJAMIENTO (
    ID_ESTABLECIMIENTO INT NOT NULL,
    NUMERO_UNIDAD INT NOT NULL,
    NOMBRE_UNIDAD VARCHAR(50),
    CAPACIDAD_MAXIMA INT NOT NULL,
    ESTADO VARCHAR(20) CHECK (ESTADO IN ('DISPONIBLE', 'OCUPADA', 'MANTENIMIENTO')) DEFAULT 'DISPONIBLE',
    PRECIO_BASE_NOCHE FLOAT NOT NULL,
    DESCRIPCION VARCHAR(MAX),
    PRIMARY KEY (ID_ESTABLECIMIENTO, NUMERO_UNIDAD),
    CONSTRAINT FK_UNIDAD_ESTABLECIMIENTO FOREIGN KEY (ID_ESTABLECIMIENTO) 
        REFERENCES ESTABLECIMIENTOS(ID_ESTABLECIMIENTO)
);

CREATE TABLE CLIENTELA (
    ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
    DNI_NIE VARCHAR(20) UNIQUE NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100)
);

CREATE TABLE RESERVAS (
    ID_RESERVA INT PRIMARY KEY IDENTITY(1,1),
    ID_CLIENTE INT NOT NULL,
    ID_ESTABLECIMIENTO INT NOT NULL,
    NUMERO_UNIDAD INT NOT NULL,
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    FECHA_ENTRADA DATE NOT NULL,
    FECHA_SALIDA DATE NOT NULL,
    NUMERO_PERSONAS INT NOT NULL,
    ESTADO VARCHAR(15) CHECK (ESTADO IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'FINALIZADA')) DEFAULT 'PENDIENTE',
    FIANZA FLOAT NULL,
    IMPORTE_ESTIMADO FLOAT NOT NULL,
    CONSTRAINT FK_RESERVA_UNIDAD FOREIGN KEY (ID_ESTABLECIMIENTO, NUMERO_UNIDAD) 
        REFERENCES UNIDADES_ALOJAMIENTO(ID_ESTABLECIMIENTO, NUMERO_UNIDAD),
    CONSTRAINT FK_RESERVA_CLIENTE FOREIGN KEY (ID_CLIENTE) 
        REFERENCES CLIENTELA(ID_CLIENTE)
);

CREATE TABLE PAGOS (
    ID_PAGO INT PRIMARY KEY IDENTITY(1,1),
    ID_RESERVA INT NOT NULL,
    IMPORTE FLOAT NOT NULL,
    FECHA_PAGO DATETIME NULL,
    METODO_PAGO VARCHAR(50),
    CONSTRAINT FK_PAGO_RESERVA FOREIGN KEY (ID_RESERVA) 
        REFERENCES RESERVAS(ID_RESERVA)
);
GO

-- 3. INSERCIÓN DE DATOS

-- Categorías
INSERT INTO CATEGORIAS (NOMBRE) VALUES ('Hotel 3 Estrellas'), ('Casa Rural'), ('Apartamento Turístico');

-- Establecimientos
INSERT INTO ESTABLECIMIENTOS (NOMBRE_COMERCIAL, DIRECCION, TELEFONO, EMAIL, ID_CATEGORIA) VALUES 
('Hotel Sol y Playa', 'Avenida Marítima 12', '912345678', 'contacto@solyplaya.com', 1),
('Casa Rural El Pinar', 'Camino del Bosque s/n', '987654321', 'info@elpinar.com', 2);

-- Unidades de Alojamiento
INSERT INTO UNIDADES_ALOJAMIENTO (ID_ESTABLECIMIENTO, NUMERO_UNIDAD, NOMBRE_UNIDAD, CAPACIDAD_MAXIMA, ESTADO, PRECIO_BASE_NOCHE, DESCRIPCION) VALUES 
(1, 101, 'Habitación Doble Estándar', 2, 'DISPONIBLE', 50.0, 'Habitación con vistas al mar'),
(1, 102, 'Suite Premium', 4, 'DISPONIBLE', 120.0, 'Suite amplia con jacuzzi'),
(2, 1, 'Casa Completa', 8, 'DISPONIBLE', 200.0, 'Casa rural entera con jardín y barbacoa');

-- Clientela
INSERT INTO CLIENTELA (DNI_NIE, NOMBRE, TELEFONO, EMAIL) VALUES 
('12345678A', 'Juan Pérez', '600111222', 'juan.perez@email.com'),
('87654321B', 'María Gómez', '600333444', 'maria.gomez@email.com');

-- Reservas
INSERT INTO RESERVAS (ID_CLIENTE, ID_ESTABLECIMIENTO, NUMERO_UNIDAD, FECHA_ENTRADA, FECHA_SALIDA, NUMERO_PERSONAS, ESTADO, FIANZA, IMPORTE_ESTIMADO) VALUES 
(1, 1, 101, '2026-06-01', '2026-06-05', 2, 'CONFIRMADA', 0, 200.0),
(2, 2, 1, '2026-07-10', '2026-07-15', 6, 'PENDIENTE', 50.0, 1050.0);

-- Pagos
INSERT INTO PAGOS (ID_RESERVA, IMPORTE, FECHA_PAGO, METODO_PAGO) VALUES 
(1, 200.0, '2026-05-10 10:30:00', 'Tarjeta'),
(2, 50.0, '2026-05-12 12:00:00', 'Transferencia');
GO
